spring:
  application:
    name: MINIO-UPLOAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/minio
    username: root
    password: 12345678
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minio
  secret-key: 12345678
  bucket: minio-upload

# swagger 配置
springdoc:
  swagger-ui:
    # 配置 swagger ui 路径
    path: /swagger-ui.html
    # 开启 swagger 页面
    enabled: true
  api-docs:
    # swagger 文档访问路径
    path: /v3/api-docs
    # 开启 swagger 文档
    enabled: true
  # 注解包扫描路径
  packages-to-scan: com.roukaixin

# knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8081