spring:
  application:
    name: MINIO-UPLOAD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.128:3306/minio
    username: root
    password: "!Aa13536431379"
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
minio:
  endpoint: http://192.168.153.128:9000
  access-key: minio
  secret-key: "!Aa13536431379"
  bucket: minio-upload

# swagger 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 配置 swagger ui 路径
    enabled: true # 开启 swagger 页面
  api-docs:
    path: /v3/api-docs # swagger 文档访问路径
    enabled: true # 开启 swagger 文档
  packages-to-scan: com.kai # 注解包扫描路径
#  paths-to-match: url 扫描

# knife4j 配置
knife4j:
  enable: true
  openapi:
    license-url: /v3/api-docs
server:
  port: 8081